wt-bot: Remove empty MSI archives.
Empty MSI archives are detected by verifying their checksum and if that
check fails it's useful to keep the bad MSI file for diagnosis. But if
the file is empty (typically because of an invalid download URL) there
is no point leaving the file around.

Signed-off-by: Francois Gouget <fgouget@free.fr>

diff --git a/wt-bot b/wt-bot
--- a/wt-bot
+++ b/wt-bot
@@ -612,6 +612,12 @@ download_msi_addon()
         mkdir -p `dirname "$addon_path"`
         url="$BASE_ADDON_URL/wine-$addon/$version/$addon_base"
         $urlget "$url" >"$addon_path"
+        if [ ! -s "$addon_path" ]
+        then
+            rm -f "$addon_path"
+            error "$addon_path is empty, aborting"
+            exit 1
+        fi
         if ! verify_addon "$key" "$addon_base" "$addon_path"
         then
             error "the $addon_base checksum does not match, aborting"
