wt-install-dev: Add the --cmd-log option.
This allows saving all the commands that are run to setup up the system
to a shell script. That script can then be used to document the process
or to reproduce it later on another machine.

Signed-off-by: Francois Gouget <fgouget@free.fr>

diff --git a/wt-install-dev b/wt-install-dev
--- a/wt-install-dev
+++ b/wt-install-dev
@@ -32,6 +32,10 @@ dry_run()
 {
     local rc
     echo "$@"
+
+    # This assumes that the command does not need quoting
+    [ -n "$opt_cmd_log" ] && echo "$@" >>"$opt_cmd_log"
+
     [ "$opt_dry_run" = "1" ] && return 0
     "$@"
     rc=$?
@@ -1051,6 +1055,21 @@ wt_parse_cmdline()
         --workarounds) opt_workarounds="1" ;;
         --yes)        opt_yes="-y";;
         --dry-run)    opt_dry_run="1" ;;
+        --cmd-log)
+            if [ -n "$opt_cmd_log" ]
+            then
+                error "--cmd-log can only be specified once"
+                usage=2 # but continue processing options
+            fi
+            if [ $# -eq 0 ]
+            then
+                error "missing value for --cmd-log"
+                usage=2
+            else
+                opt_cmd_log="$1"
+                shift
+            fi
+            ;;
         --help|-h|-?)
             usage=0
             break
@@ -1080,7 +1099,7 @@ wt_parse_cmdline()
 
     if [ "$usage" = "0" ]
     then
-        echo "Usage: $name0 [--no-wine] [--no-extra] [--tests] [--wt-daily] [--packages] [--workarounds] [--yes] [--dry-run] [--help]"
+        echo "Usage: $name0 [--no-wine] [--no-extra] [--tests] [--wt-daily] [--packages] [--workarounds] [--yes] [--cmd-log SCRIPT] [--dry-run] [--help]"
         echo
 
         echo "Installs the packages needed to build the 32- and 64-bit versions of Wine. When possible applies workarounds if installing both the 32- and 64-bit development packages is impossible. Can also install some extra packages needed by the tests and the wt-daily scripts."
@@ -1103,6 +1122,7 @@ wt_parse_cmdline()
         echo "  --workarounds Apply workarounds for packages that don't support multiarch so"
         echo "               that both the 32- and 64-bit versions of Wine can be built."
         echo "  --yes        Answer yes to all package installation prompts."
+        echo "  --cmd-log SCRIPT Saves all commands being run to the specified shell script."
         echo "  --dry-run    Only show which actions would be taken."
         echo "  --help, -h   Shows this help message."
         exit 0
@@ -1111,6 +1131,20 @@ wt_parse_cmdline()
         error "try '$name0 --help' for more information"
         exit $usage
     fi
+}
+
+wt_build_cmdargs()
+{
+    # Rebuild a cleaner, more explicit command line for --cmd-log
+    wt_cmdargs=""
+    [ "$opt_wine" = "1" ] && wt_cmdargs="$wt_cmdargs --wine"
+    [ "$opt_wine_extra" = "1" ] && wt_cmdargs="$wt_cmdargs --extra"
+    [ "$opt_wine_tests" = "1" ] && wt_cmdargs="$wt_cmdargs --tests"
+    [ "$opt_wt_daily" = "1" ] && wt_cmdargs="$wt_cmdargs --wt-daily"
+    [ "$opt_packages" = "1" ] && wt_cmdargs="$wt_cmdargs --packages"
+    [ "$opt_workarounds" = "1" ] && wt_cmdargs="$wt_cmdargs --workarounds"
+    [ "$opt_yes" = "1" ] && wt_cmdargs="$wt_cmdargs --yes"
+    [ "$opt_dry_run" = "1" ] && wt_cmdargs="$wt_cmdargs --dry-run"
 }
 
 
@@ -1133,6 +1167,29 @@ wt_init()
         exit 1
     fi
     ${wt_platform}_init
+    if [ -n "$opt_cmd_log" ]
+    then
+        (
+            echo "#!/bin/sh"
+            echo "# Generated by $name0$wt_cmdargs"
+            . /etc/os-release
+            echo "# For the '$wt_platform' platform on $PRETTY_NAME"
+            echo "# These commands may not be applicable to any other platform."
+            if [ "$opt_dry_run" = "1" ]
+            then
+                echo "# *** WARNING ***"
+                echo "# In --dry-run mode the workarounds will likely be incorrect or incomplete."
+            fi
+            echo "set -x"
+            echo
+        ) >"$opt_cmd_log"
+        if [ $? -ne 0 ]
+        then
+            error "could not generate the --cmd-log script"
+            exit 1
+        fi
+        chmod +x "$opt_cmd_log"
+    fi
 }
 
 wt_pre_install()
@@ -1205,7 +1262,9 @@ then
     opt_workarounds=""
     opt_yes=""
     opt_dry_run=""
+    opt_cmd_log=""
     wt_parse_cmdline "$@"
+    wt_build_cmdargs
     wt_init
     wt_pre_install
     wt_install
