wt-install-dev: Add support for adding an apt section.
This allows adding the Microsoft TrueType fonts without manual
intervention.

Signed-off-by: Francois Gouget <fgouget@free.fr>

diff --git a/wt-install-dev b/wt-install-dev
--- a/wt-install-dev
+++ b/wt-install-dev
@@ -195,6 +195,46 @@ apt_check()
     LANG= apt-cache "$action" "$pkg" 2>/dev/null | egrep -q "$@"
 }
 
+# apt_addsection <landmark> <section> <packages>
+#
+# Checks if the <landmark> package is available and returns immediately if it
+# is. Otherwise asks whether <section> should be added to the apt sources.
+# If --yes was given or the user agrees the section is added but
+# 'apt-get update' is not called.
+#
+# Returns 0 if a section was added, non-zero otherwise.
+apt_addsection()
+{
+    local a pkg
+    local landmark="$1"
+    local section="$2"
+    local packages="$3"
+
+    # Can the section even be added?
+    command -v apt-add-repository >/dev/null 2>&1 || return 1
+
+    # Does it need to be added?
+    pkg=`echo "$landmark" | sed -e "s/:.*//g"`
+    apt_check show "$landmark" "Package: $pkg" && return 1
+
+    echo
+    echo "********************"
+    echo
+    echo "The $section section is needed for $packages."
+    echo
+    echo -n "Do you want to add it? [Y/n] "
+    if [ -n "$opt_yes" ]
+    then
+        echo "yes"
+        a="y"
+    else
+        read a
+    fi
+    [ -z "$a" -o "$a" = "y" -o "$a" = "Y" ] || return 1
+
+    dry_run apt-add-repository "$section"
+}
+
 # apt_pkg [--test] <pkg1> ...
 #
 # If <pkg1> exists, schedule it for installation and return success.
@@ -473,6 +513,9 @@ apt_wine_extra()
 
 apt_wine_tests()
 {
+    apt_addsection ttf-mscorefonts-installer contrib "the Microsoft TrueType fonts packages" &&
+        dry_run apt-get update
+
     # GStreamer plugins for the quartz (winegstreamer) tests
     apt_multi gstreamer1.0-libav
 
