wt-install-dev: Make the wt_create_so*() functions more generic.
They now get the path of the library directories from the
distribution-specific init() function and make no assumption on the
architecture name.
This allows reusing these functions on other Linux distributions.

Signed-off-by: Francois Gouget <fgouget@free.fr>

diff --git a/wt-install-dev b/wt-install-dev
--- a/wt-install-dev
+++ b/wt-install-dev
@@ -41,9 +41,78 @@ dry_run()
 }
 
 
+#####
+#
+# Generic helpers
+#
+#####
+
 pkginstall=""
 pkgbroken=""
 pkgmissing=""
+
+
+wt_libdirs=""
+wt_create_so_warn=1
+
+wt_create_so()
+{
+    sodev="$1"
+    solib="$2"
+    [ -n "$solib" ] || solib="$sodev"
+    if [ -z "$wt_libdirs" ]
+    then
+        error "the per-distribution code must set \$wt_libdirs"
+        exit 1
+    fi
+
+    rc=0
+    for libdir in $wt_libdirs
+    do
+        usrlibdir="/usr$libdir"
+        if [ ! -f "$usrlibdir/$sodev.so" ]
+        then
+            sover=`cd "$usrlibdir" 2>/dev/null && ls "$solib.so".[0-9]* 2>/dev/null | head -n1`
+            if [ ! -f "$usrlibdir/$sover" ]
+            then
+                # We want the full path in this case
+                sover=`ls "$libdir/$solib.so".[0-9]* 2>/dev/null | head -n1`
+                [ -f "$sover" ] || sover=""
+            fi
+
+            # Use -f because $sodev.so may be a broken symlink
+            if [ -z "$sover" ] || \
+                   ! dry_run ln -s -f "$sover" "$usrlibdir/$sodev.so"
+            then
+                error "Could not create the ...$libdir/$sodev.so symbolic link for $pkg"
+                rc=1
+            fi
+        fi
+    done
+    if [ $rc -ne 0 -a -n "$wt_create_so_warn" ]
+    then
+        wt_create_so_warn=
+        warning "The .so symlink creation will fail if the non-dev package is not installed."
+        [ -n "$opt_dry_run" ] && warning "This is particularly likely with --dry-run."
+    fi
+    return $rc
+}
+
+wt_create_sos()
+{
+    pkg="$1"
+    shift
+
+    success=1
+    for lib in "$@"
+    do
+        wt_create_so "$lib" || success=
+    done
+    if [ -n "$success" ]
+    then
+        pkgbroken=`echo "$pkgbroken" | sed -e "s/$pkg:[a-z0-9]*//"`
+    fi
+}
 
 
 #####
@@ -142,63 +211,6 @@ deb_install()
     echo
 }
 
-deb_create_so_warn=1
-
-deb_create_so()
-{
-    sodev="$1"
-    solib="$2"
-    [ -n "$solib" ] || solib="$sodev"
-
-    rc=0
-    for arch in x86_64 i386
-    do
-        libdir="/lib/$arch-linux-gnu"
-        usrlibdir="/usr$libdir"
-        if [ ! -f "$usrlibdir/$sodev.so" ]
-        then
-            sover=`cd "$usrlibdir" 2>/dev/null && ls "$solib.so".[0-9]* 2>/dev/null | head -n1`
-            if [ ! -f "$usrlibdir/$sover" ]
-            then
-                # We want the full path in this case
-                sover=`ls "$libdir/$solib.so".[0-9]* 2>/dev/null | head -n1`
-                [ -f "$sover" ] || sover=""
-            fi
-
-            # Use -f because $sodev.so may be a broken symlink
-            if [ -z "$sover" ] || \
-                   ! dry_run ln -s -f "$sover" "$usrlibdir/$sodev.so"
-            then
-                error "Could not create the $arch $sodev.so symbolic link for $pkg"
-                rc=1
-            fi
-        fi
-    done
-    if [ $rc -ne 0 -a -n "$deb_create_so_warn" ]
-    then
-        deb_create_so_warn=
-        warning "The .so symlink creation will fail if the non-dev package is not installed."
-        [ -n "$opt_dry_run" ] && warning "This is particularly likely with --dry-run."
-    fi
-    return $rc
-}
-
-deb_create_sos()
-{
-    pkg="$1"
-    shift
-
-    success=1
-    for lib in "$@"
-    do
-        deb_create_so "$lib" || success=
-    done
-    if [ -n "$success" ]
-    then
-        pkgbroken=`echo "$pkgbroken" | sed -e "s/$pkg:[a-z0-9]*//"`
-    fi
-}
-
 
 #
 # Debian: Base Wine dependencies
@@ -216,6 +228,7 @@ deb_init()
         dry_run dpkg --add-architecture i386
         dry_run apt-get update
     fi
+    wt_libdirs="/lib/i386-linux-gnu /lib/x86_64-linux-gnu"
 }
 
 deb_wine()
@@ -359,17 +372,17 @@ deb_workarounds()
     # Work around the missing or broken multiarch support where possible
 
     # Needed for Debian 10
-    deb_create_sos libsdl2-dev libSDL2-2.0 # Broken up to 2.0.9
-    deb_create_so libSDL2 libSDL2-2.0
+    wt_create_sos libsdl2-dev libSDL2-2.0 # Broken up to 2.0.9
+    wt_create_so libSDL2 libSDL2-2.0
 
     # Needed for Ubuntu 18.04
-    deb_create_sos libcups2-dev libcups
-    deb_create_sos libfontconfig1-dev libfontconfig
-    deb_create_sos libfreetype6-dev libfreetype
-    deb_create_sos libgnutls28-dev libgnutls
-    deb_create_sos libpcap0.8-dev libpcap
-    deb_create_sos libtiff-dev libtiff
-    deb_create_sos libgstreamer-plugins-base1.0-dev libgstaudio-1.0 libgstbase-1.0 libgstreamer-1.0 libgstvideo-1.0
+    wt_create_sos libcups2-dev libcups
+    wt_create_sos libfontconfig1-dev libfontconfig
+    wt_create_sos libfreetype6-dev libfreetype
+    wt_create_sos libgnutls28-dev libgnutls
+    wt_create_sos libpcap0.8-dev libpcap
+    wt_create_sos libtiff-dev libtiff
+    wt_create_sos libgstreamer-plugins-base1.0-dev libgstaudio-1.0 libgstbase-1.0 libgstreamer-1.0 libgstvideo-1.0
 
     # Ubuntu 18.04 is missing libxslt/xsltconfig.h
     xsltconfig="libxslt/xsltconfig.h"
@@ -388,14 +401,14 @@ deb_workarounds()
     fi
 
     # Needed for Debian 9
-    deb_create_sos libgphoto2-dev libgphoto2 libgphoto2_port
-    deb_create_sos libjpeg62-turbo-dev libjpeg
-    deb_create_sos libkrb5-dev libcom_err libgssapi_krb5 libk5crypto libkrb5
-    deb_create_sos libpulse-dev libpulse
-    deb_create_sos libsane-dev libsane
-    deb_create_sos libxml2-dev libxml2
-    deb_create_sos libxslt1-dev libxslt
-    deb_create_sos unixodbc-dev libodbc
+    wt_create_sos libgphoto2-dev libgphoto2 libgphoto2_port
+    wt_create_sos libjpeg62-turbo-dev libjpeg
+    wt_create_sos libkrb5-dev libcom_err libgssapi_krb5 libk5crypto libkrb5
+    wt_create_sos libpulse-dev libpulse
+    wt_create_sos libsane-dev libsane
+    wt_create_sos libxml2-dev libxml2
+    wt_create_sos libxslt1-dev libxslt
+    wt_create_sos unixodbc-dev libodbc
 
     # The GStreamer issues cannot be worked around
 }
